### PR TITLE
1.5

### PR DESCRIPTION
**Pull request by lucashby**
This implementation provides an implementation for the latest release of Hangfire.Core, version 1.5.0.0, which has improved support for IoC containers.  It also brings StructureMap up-to-date to version 3.1.6.186 and takes advantage of StructureMap's nested containers for Hangfire's recently introduced JobActivatorScope.  Added a BackgroundJobLifecycle to ensure dependencies are created/disposed within scope for proper object cleanup.

I also went ahead and updated the README.md to be more inline with Hangfire.Autofac and Hangfire.Ninject.

I have enjoyed using your NuGet package and would love to see it updated for the new Hangfire 1.5.  Please take my effort and improve as necessary!

### CODE REVIEW

**Comment by cocowalla** [comment]
Nice, thanks for this :)

**Comment by lucashby** [comment]
You may want to pop it open and bump the Hangfire dep to 1.5.1. Looks like they released a quick patch since I did this. Also, I did not mess with any of the NuGet files, so if you decide to publish, you'll want to do that part. Thank you so much for getting back to me! I hope your work travels went well.

On Oct 15, 2015 4:42 AM, cocowalla notifications@github.com wrote:
Nice, thanks for this :)

---

**Comment by darrencauthon** [comment]
@cocowalla 

It seems that the work is done to upgrade... why not upgrade and push to NuGet?

Or instead, why not bump the max version for `Hangfire` to pre-1.5?  Because this project is not compatible with 1.5, yet Nuget will allow the installation with it.

Today, if someone (like me) imports this project and tries to run it against Hangfire 1.5, they'll just get errors.

**Comment by cocowalla** [comment]
Sorry, been meaning to get around to this for a while - promise to do it soon!!

**Comment by darrencauthon** [comment]
@cocowalla 

Thank you for updating the nuget package!  Now I can remove this dll and point at nuget instead.  Package management is nice.

**Comment by cocowalla** [comment]
No worries - sorry it took me so long to do it!

**Pull request merged**
